wandb_version: 1

abs_path:
  desc: null
  value: /home/sara/code/ratolins/code/
sequence_length:
  desc: null
  value:
  - 300
  - 600
backbone:
  desc: null
  value: resnet
layers:
  desc: null
  value: lstm
dropout_rate:
  desc: null
  value: 0.5
num_layers:
  desc: null
  value:
  - 1
  - 2
  - 3
num_units:
  desc: null
  value:
  - 64
  - 128
loss:
  desc: null
  value: binary_crossentropy
optimizer:
  desc: null
  value: adam
learning_rate:
  desc: null
  value: 0.001
epochs:
  desc: null
  value: 50
batch_size:
  desc: null
  value:
  - 8
  - 16
es_monitor:
  desc: null
  value: val_prc
es_mode:
  desc: null
  value: max
es_patience:
  desc: null
  value: 5
reuse_actors:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.15.12
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1697705201.349428
    t:
      1:
      - 55
      3:
      - 16
      - 23
      4: 3.10.10
      5: 0.15.12
      8:
      - 1
      - 5
      13: darwin-arm64
