wandb_version: 1

abs_path:
  value: /home/sara/code/ratolins/code/
backbone:
  value: resnet
batch_size:
  value: 16
dropout_rate:
  value: 0.5
epochs:
  value: 50
es_mode:
  value: max
es_monitor:
  value: val_prc
es_patience:
  value: 5
layers:
  value: lstm
learning_rate:
  value: 0.001
loss:
  value: binary_crossentropy
num_layers:
  value: 3
num_units:
  value: 256
optimizer:
  value: adam
reuse_actors:
  value: false
sequence_length:
  value: 1200
